# Use the official Golang image
FROM golang:1.25.4-bookworm

# Set the working directory
WORKDIR /app

# Copy go.mod and go.sum
COPY go.mod go.sum ./

# Download dependencies
RUN go mod download

# Copy the rest of the source code
COPY . .

# Default command to run all tests
CMD ["go", "test", "-race", "-v", "./internal/server/..."]
