services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.native
    command: ["./jedis", "-mode=sharding", "-cpus=4"]
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          cpus: '4.0'
