FROM golang:1.25.4-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
# Compile specific native optimizations and disable CGO to ensure it runs cleanly on alpine
RUN CGO_ENABLED=0 GOOS=linux go build -o jedis cmd/main.go

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/jedis .

# Expose port and run
EXPOSE 6379
CMD ["./jedis"]
